spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://152.136.252.57:3306/mydb?characterEncoding=UTF-8
    username: mydb
    password: mydb
  mail:
    host: smtp.qq.com
    username: 2494091497@qq.com
    password: qblfldvnicuiebcd
    default-encoding: utf-8
    enable: true
    port: 465
    socketFactory:
      port: 465
      class: javax.net.ssl.SSLSocketFactory
      fallback: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
    map-underscore-to-camel-case: false #
server:
  port: 443

file:
  uploadurl: "/upload/file/"
  localurl: "D:/upload/resource/file/"
